# Generated by Django 4.0 on 2026-01-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('population', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('text', models.CharField(max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.country')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('stringency_index', models.FloatField(blank=True, null=True)),
                ('c1_school_closing', models.IntegerField(blank=True, null=True)),
                ('c2_workplace_closing', models.IntegerField(blank=True, null=True)),
                ('c6_stay_at_home', models.IntegerField(blank=True, null=True)),
                ('c8_international_travel_controls', models.IntegerField(blank=True, null=True)),
                ('h6_facial_coverings', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='dashboard.country')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_cases_smoothed', models.FloatField(blank=True, null=True)),
                ('new_deaths_smoothed', models.FloatField(blank=True, null=True)),
                ('total_cases', models.FloatField(blank=True, null=True)),
                ('total_deaths', models.FloatField(blank=True, null=True)),
                ('cases_per_million', models.FloatField(blank=True, null=True)),
                ('deaths_per_million', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.country')),
            ],
        ),
        migrations.AddIndex(
            model_name='policyevent',
            index=models.Index(fields=['country', 'date'], name='dashboard_p_country_ea5315_idx'),
        ),
        migrations.AddIndex(
            model_name='policydaily',
            index=models.Index(fields=['country', 'date'], name='dashboard_p_country_f5df1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policydaily',
            unique_together={('country', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['country', 'date'], name='dashboard_d_country_7a079c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetric',
            unique_together={('country', 'date')},
        ),
    ]
