# Generated by Django 4.0 on 2026-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='new_vaccinations_smoothed_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='people_fully_vaccinated_per_hundred',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='people_vaccinated_per_hundred',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='total_vaccinations_per_hundred',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
