# Generated by Django 4.0 on 2026-01-31 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailymetric_new_vaccinations_smoothed_per_million_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymetric',
            name='new_vaccinations_smoothed_per_million',
        ),
        migrations.RemoveField(
            model_name='dailymetric',
            name='people_vaccinated_per_hundred',
        ),
    ]
